package:
  name: dartsdk
  version: "1.22.1"

source:
  git_rev: v1.22.1
  git_url: https://github.com/dart-lang/sdk.git

about:
  home: https://github.com/dart-lang/sdk
  license: 
  license_file: LICENSE
